Fix one AgentName index in Auth graph
This is something we noticed at the 2024-08-23 meeting.

Note: ROBOT would fail to convert the OWL then
citing the following error:

org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://www.ica.org/standards/RiC/ontology> Cause: www.ica.org
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.

I understand now that this was simply due to a lack
of internet access.